### ISSUE TITLE
Responses with multiple representations are not handled properly

### ISSUE THREAD

**Issue by anestos** [curityio/ios-haapi-demo-app#4]
Responses with multiple representations, for example the BankID Polling step which contains the BankID autostart URI and a QR code are not triggering the ClientOperationStep. Instead they are used as HaapiRepresentations.

The problem can be identified in the switch in line 117 of FlowViewModel.swift

**Comment by gary-archer** [comment]
BankID is the main use case and works now for same device. A separate issue has been raised for the cross device case where there was a bug. If there are further multi-representation use cases in future we can raise additional tickets.
